// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: codes.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createCode = `-- name: CreateCode :one
INSERT INTO codes (
  code,
  user_id,
  expires_at
) VALUES ($1, $2, $3) RETURNING id, code, user_id, used, created_at, expires_at
`

type CreateCodeParams struct {
	Code      string    `json:"code"`
	UserID    uuid.UUID `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateCode(ctx context.Context, arg CreateCodeParams) (Code, error) {
	row := q.db.QueryRowContext(ctx, createCode, arg.Code, arg.UserID, arg.ExpiresAt)
	var i Code
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.UserID,
		&i.Used,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteCode = `-- name: DeleteCode :exec
DELETE FROM codes WHERE id = $1
`

func (q *Queries) DeleteCode(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCode, id)
	return err
}

const deleteExpiredCodes = `-- name: DeleteExpiredCodes :exec
DELETE FROM codes WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredCodes(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredCodes)
	return err
}

const getCode = `-- name: GetCode :one
SELECT id, code, user_id, used, created_at, expires_at FROM codes WHERE user_id = $1 AND code = $2 AND used = FALSE AND expires_at > NOW() LIMIT 1
`

type GetCodeParams struct {
	UserID uuid.UUID `json:"user_id"`
	Code   string    `json:"code"`
}

func (q *Queries) GetCode(ctx context.Context, arg GetCodeParams) (Code, error) {
	row := q.db.QueryRowContext(ctx, getCode, arg.UserID, arg.Code)
	var i Code
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.UserID,
		&i.Used,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const markCodeUsed = `-- name: MarkCodeUsed :exec
UPDATE codes SET used = TRUE where id = $1 AND used = FALSE
`

func (q *Queries) MarkCodeUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markCodeUsed, id)
	return err
}
