// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Code struct {
	ID        uuid.UUID    `json:"id"`
	Code      string       `json:"code"`
	UserID    uuid.UUID    `json:"user_id"`
	Used      sql.NullBool `json:"used"`
	CreatedAt time.Time    `json:"created_at"`
	ExpiresAt time.Time    `json:"expires_at"`
}

type User struct {
	ID            uuid.UUID      `json:"id"`
	Username      sql.NullString `json:"username"`
	Email         string         `json:"email"`
	ProfilePicUrl sql.NullString `json:"profile_pic_url"`
	Verified      sql.NullBool   `json:"verified"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}
